### ISSUE TITLE
Create build using Stephen's RHEL roles

### ISSUE THREAD

**Issue by ksclarke** [UCLALibrary/packer-samvera#38]
The current build works with DCE's Ubuntu roles. We want one that works with RHEL/CentOS too. I think it's still wise to maintain the build based on DCE roles since that's really the upstream, but this ticket is for adding RHEL/CentOS builds too.

I think it's wise to wait until Stephen says "These are done" though before starting to attempt this. Even better, if Hardy is doing a Vagrant test environment for the RHEL roles, wait until he's done too (since he will have worked out some of the potential kinks involved with running the roles on a single VM). If Hardy isn't doing that though, proceed with this as soon as Stephen hits a "finished" point.

**Comment by ksclarke** [comment]
Stephen has documentation how to build everything on a single VM instance using RHEL. Hardy has a build doing the same on CentOS (but with some forked roles). Time to make it work with packer-samvera using CentOS and only Stephen's roles (no forked versions).

**Comment by kjallen** [comment]
We discussed during standup, and @ksclarke , group had some thoughts about restructuring into individual tickets or a way to measure effectively (ie way to measure progress)

**Comment by ksclarke** [comment]
Yes, in retrospect, this should have been multiple tickets, I agree. I expect to close it today though so it's too late to restructure now.

**Comment by ksclarke** [comment]
v0.3 up on Vagrant Cloud is centos-based. Issues with it can be filed as smaller tickets.
