### ISSUE TITLE
`vagrant halt` fails, probably because `shutdown -h now` is not run as root

### ISSUE THREAD

**Issue by sourcefilter** [UCLALibrary/packer-samvera#55]
```
andy@YRL-ML-DLP704:californica$ vagrant halt
==> default: Attempting graceful shutdown of VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

shutdown -h now

Stdout from the command:



Stderr from the command:

bash: line 5: shutdown: command not found
```

Forgot to take notes, but `shutdown now -h` inside the VM shell fails with a similar "command not found" message. `sudo shutdown now -h` works, but I assume there's other vagrant stuff (like w/ the sshfs mount) that might not get done.

So, acceptance criteria (now that the problem is understood):
- [x] Create a uclalib_role_developers_box Ansible role
- [x] Create tests for uclalib_role_developers_box that run with Travis config
- [x] Update packer-samvera to pull in and use the uclalib_role_developers_box role
- [x] Confirm that `vagrant halt` works for the dev box published to Vagrant Cloud

**Comment by ksclarke** [comment]
This sounds like RHEL/CentOS wants the full path to shutdown. It's more particular than Ubuntu. Investigating...

**Comment by ksclarke** [comment]
[vagrant@localhost ~]$ shutdown -h now
==== AUTHENTICATING FOR org.freedesktop.login1.power-off ===
Authentication is required for powering off the system.
Authenticating as: vagrant
Password:

**Comment by ksclarke** [comment]
The code to fix this is in https://github.com/UCLALibrary/uclalib_role_samvera_capdeploy/pull/29 but in talking with Stephen we decided to break this out into its own role. So, I'll write an Ansible role that will handle stuff specific to the developer's box.

**Comment by ksclarke** [comment]
Just dropping this bit of documentation in here so it's not forgotten: https://blog.learningtree.com/policykit-authentication-framework-creating-rules/

**Comment by ksclarke** [comment]
Do a `vagrant box update` to download the latest version with this fix. Auto-updates for boxes are turned off by default.
