### ISSUE TITLE
Feature suggestion: add ursus to the californica VM

### ISSUE THREAD

**Issue by sourcefilter** [UCLALibrary/packer-samvera#57]
Since work is beginning on ursus, it would be nice to add it to the VM. It should:
- [ ] share californica's solr index
- [ ] add a sshfs mount
- [ ] ... ?

**Comment by ksclarke** [comment]
:+1:

I agree this should be done. I'm hoping someone will document the Ursus build process a little so I can crib off that. Thanks for opening this ticket though. Now at least it's in our waffle "inbox" so we can prioritize it.

**Comment by ksclarke** [comment]
I'm going to close this as a duplicate of #60. Though I think this ticket went in an hour or two earlier, there are links between #60 and a documentation ticket which I think are important to keep.
