### ISSUE TITLE
Output a nice error message if vagrant-sshfs isn't installed

### ISSUE THREAD

**Issue by ksclarke** [UCLALibrary/packer-samvera#8]
Right now, the output when you run without reading the requirements in the README is a little cryptic. It'd be nice if a clear error message told you that you need to install SSHFS and vagrant-sshfs in order to take advantage of the VM's shared/synced folder.

**Comment by hardyoyo** [comment]
https://github.com/ksclarke/packer-samvera/pull/5 addresses this, and has been merged
