### ISSUE TITLE
Write Ansible role to set file and process limit on OS

### ISSUE THREAD

**Issue by ksclarke** [UCLALibrary/packer-samvera#9]
Should these values warned about by Solr be bumped up by the ansible-samvera roles?

```
vagrant@localhost:~/samvera-mgmt$ bundle exec rake hydra:server
rake aborted!
Failed to execute solr start: *** [WARN] *** Your open file limit is currently 1024.  
 It should be set to 65000 to avoid operational disruption. 
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
*** [WARN] ***  Your Max Processes Limit is currently 15656. 
 It should be set to 65000 to avoid operational disruption. 
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
```

**Comment by bess** [comment]
Oh, interesting. I don't get those. But yes, those should be bumped up. You will definitely hit errors if you're using solr heavily and you have such a low file limit.

**Comment by mark-dce** [comment]
@ksclarke I notice that you're invoking `hydra:server` which probably means you're launching solr_wrapper rather than the solr installed by ansible.  I think the solr config parameters for solr_wrapper are set slightly differently than you would for a full solr install.

If you're using full versions of Solr and Fedora installed by ansible, you shouldn't need to run `bundle exec rake hydra:server`, you should just need to point `config/solr.yml` and `config/fedora.yml` at the installed versions' respective ports and call `bundle exec rails server` to start the application.

**Comment by ksclarke** [comment]
Thanks @mark-dce -- Yes, I'm not running hydra:server anymore since everything is already running on the VM, thanks. Was just doing that when I was trying to follow the README (without realizing some of it was irrelevant for the VM -- a little bit of flailing around on my part).

I think those settings (file and process limits) are OS level, though, right? So I'll still need to modify them in the ansible roles or am I mistaken about that?

**Comment by bess** [comment]
@ksclarke Yes, I think you need to modify them in the ansible roles. I believe those settings are OS level, you're right.

**Comment by ksclarke** [comment]
Notes to self:

* Open files for system is fine (and imagine it would be on any system). Set open file limit for the Solr user to what Solr recommends: 65000.
* Max processes for system and solr user are lower than what Solr recommends: 65000 (system just barely)

There are two relevant ansible roles. The first sets system values. The second sets user (in our case Solr user) values:

* https://docs.ansible.com/ansible/2.6/modules/sysctl_module.html
* https://docs.ansible.com/ansible/2.5/modules/pam_limits_module.html

I have a question about bumping up max processes for the system and user. The Solr user is not the only user on the system. I'm unsure what the system setting should be, given that we don't want the Solr user eating up all the system's processes. Researching...

**Comment by ksclarke** [comment]
Just a note that Stephen is doing this using a file/template instead of using the above modules (for the Solr user at least): https://github.com/UCLALibrary/ansible_uclalib_role_solr7/blob/master/tasks/install.yml#L13

**Comment by ksclarke** [comment]
I can add what Stephen is doing to the ansible-samvera Solr role, but that doesn't address that the system (i.e., hard) max processes are lower than the 65000 suggestion for the user limit. The sysctl Ansible module will set those but I'm not sure what they should be set to. The "max user processes" on my Ubuntu system (as root: ulimit -Ha) has a default setting of 63578.

StackOverflow tells me 4194303 is the maximum process limit for x86_64 and 32767 for x86. I've read other places that it's "unlimited" and that root has no limit, yet running `ulimit -a` as root shows a limit in max user processes.

I can write the role but I may need a sysadmin to weigh in on what max processes should be at the system level. Not sure what happens if you set the solr user's max processes higher than what root has. Perhaps nothing?

**Comment by ksclarke** [comment]
Fixed, just waiting on review.
